create-pull-request: Improved the error-handling
The error handling is improved to warn the user about errors
in "git format-patch" and in case the user supplied a changeset
without any diffs.

Signed-off-by: Esben Haabendal <esben.haabendal@prevas.dk>

diff --git a/scripts/create-pull-request b/scripts/create-pull-request
--- a/scripts/create-pull-request
+++ b/scripts/create-pull-request
@@ -178,7 +178,16 @@ mkdir $ODIR
 
 # Generate the patches and cover letter
 git format-patch -M40 --subject-prefix="$PREFIX" -n -o $ODIR --thread=shallow --cover-letter $RELATIVE_TO..$COMMIT_ID > /dev/null
+if [ $? -ne 0 ]; then
+	echo "ERROR: git format-patch reported an error"
+	exit 1
+fi
 
+# Check if for some reason the ODIR is empty (could be the case if there are no diffs)
+if [ "$(ls -A $ODIR)" ==  ""  ]; then
+    echo "ERROR: Empty patch was generated - please check diffs between \"$RELATIVE_TO\" and \"$COMMIT_ID\""
+    exit 1
+fi
 
 # Customize the cover letter
 CL="$ODIR/0000-cover-letter.patch"
